---
driver:
  name: vagrant
  communicator: winrm
  gui: true

transport:
  name: winrm

provisioner:
    name: dsc
    retry_on_exit_code:
      - 35
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      action_after_reboot: StopConfiguration
      reboot_if_needed: false
      debug_mode: none
      allow_module_overwrite: true
    configuration_script_folder: examples
    configuration_script: dsc_configuration.ps1
    configuration_data_variable: configData
    configuration_name: Hubot
    modules_path: .
    modules_from_gallery:
     - xPSDesiredStateConfiguration

platforms:
- name: Win2016TP5Core
  driver:
    box: MattHodge/Win2016TP5Core
    gui: true
  provisioner:
    dsc_local_configuration_manager_version: wmf5

verifier:
  name: pester
  test_folder: Tests

suites:
  - name: default
